# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain', max_length=100)),
                ('address', models.CharField(help_text='IP Address', max_length=50)),
                ('content', models.CharField(help_text='Description about website', max_length=200)),
            ],
        ),
    ]
